CREATE USER veritymesh_app WITH PASSWORD 'veritymesh-app-local';
GRANT CONNECT ON DATABASE veritymesh TO veritymesh_app;
GRANT USAGE ON SCHEMA public TO veritymesh_app;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
REVOKE TEMPORARY ON DATABASE veritymesh FROM PUBLIC;
REVOKE CREATE ON SCHEMA public FROM veritymesh_app;
REVOKE TEMPORARY ON DATABASE veritymesh FROM veritymesh_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO veritymesh_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO veritymesh_app;
